run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gofmt
    - goimports
    - gocyclo
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

gocyclo:
  min-complexity: 15
